name:                    biology
version:                 0.1.0.0
license:                 BSD3

extra-source-files:
- README.md

dependencies:
- base                   >= 4.7 && < 5
- accelerate             == 1.3.0.0
- accelerate-llvm-native == 1.3.0.0
- attoparsec
- curl
- fused-effects
- lens-accelerate
- lens
- monad-unlift
- text
- transformers           == 0.5.6.2

executable:
  main:                  Main.hs
  source-dirs:           src
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
