resolver: lts-13.25

nix:
  enable: true
  pure: false
  packages: [ libffi curl ]

packages:
- .

extra-deps:
- git:    https://github.com/tmcdonell/accelerate.git
  commit: 1010d97f8cc8cbecff28200cf6e176455769c644

- git:    https://github.com/tmcdonell/accelerate-llvm.git
  commit: 60b0ebc38549e887159e0bec7493fad2231a2550
  subdirs:
    - accelerate-llvm
    - accelerate-llvm-native

- lens-accelerate-0.2.0.0
- llvm-hs-8.0.0
- llvm-hs-pure-8.0.0
- transformers-0.5.6.2
